Repository Mile-Writings/Mile-Server, pull requests merged in 2024-05, with the labels that each got.

#323 #322 [feat] 베스트 모임 반환 로직 구현
  module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
  module-domain/src/main/java/com/mile/moim/service/MoimService.java
Labels: highest

#327 #326 [feat] 동시성 이슈 관련 해결
  module-domain/src/main/java/com/mile/curious/service/CuriousService.java
Labels: high

#334 #333 [feat] 글모임 뷰 - 필명 수정을 위한 플로우 구현
  module-api/src/main/java/com/mile/controller/moim/MoimController.java
  module-api/src/main/java/com/mile/controller/moim/MoimControllerSwagger.java
  module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
  module-api/src/main/java/com/mile/controller/writername/WriterNameControllerSwagger.java
  module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
  module-common/src/main/java/com/mile/exception/message/SuccessMessage.java
  module-domain/src/main/java/com/mile/moim/service/MoimService.java
  module-domain/src/main/java/com/mile/writername/domain/WriterName.java
  module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
  module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionResponse.java
  module-domain/src/main/java/com/mile/writername/service/dto/WriterNameDescriptionUpdateRequest.java
  module-domain/src/main/java/com/mile/writername/service/dto/WriterNameShortResponse.java
Labels: highest

#339 #338 [chore] 이미지변경
  module-domain/src/main/java/com/mile/post/domain/Post.java
  module-domain/src/main/java/com/mile/post/service/PostCreateService.java
Labels: high

#342 #340 [feat] 중복된 요청 에러 처리
  module-api/src/main/java/com/mile/controller/comment/CommentController.java
  module-api/src/main/java/com/mile/controller/moim/MoimController.java
  module-api/src/main/java/com/mile/controller/post/PostController.java
  module-api/src/main/java/com/mile/controller/topic/TopicController.java
  module-api/src/main/java/com/mile/controller/user/UserController.java
  module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
  module-common/build.gradle
  module-common/src/main/java/com/mile/config/filter/PrincipalHandler.java
  module-common/src/main/java/com/mile/config/redis/RedisConfig.java
  module-common/src/main/java/com/mile/config/web/WebConfig.java
  module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
  module-common/src/main/java/com/mile/exception/model/TooManyRequestException.java
  module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
  module-common/src/main/java/com/mile/interceptor/DuplicatedInterceptor.java
Labels: highest

#343 #341 [feat] 글감별 글 조회 무한 스크롤(페이지네이션) 구현
  module-api/src/main/java/com/mile/controller/topic/TopicController.java
  module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
  module-common/src/main/java/com/mile/utils/SecureUrlUtil.java
  module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
  module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java
  module-domain/src/main/java/com/mile/post/service/PostGetService.java
  module-domain/src/main/java/com/mile/topic/service/TopicService.java
  module-domain/src/main/java/com/mile/topic/service/dto/PostListInTopicResponse.java
Labels: highest, high

#349 #340 [hotfix] 중복된 요청 예외처리
  module-api/src/main/java/com/mile/controller/comment/CommentController.java
  module-api/src/main/java/com/mile/controller/moim/MoimController.java
  module-api/src/main/java/com/mile/controller/post/PostController.java
  module-api/src/main/java/com/mile/controller/topic/TopicController.java
  module-api/src/main/java/com/mile/controller/user/UserController.java
  module-api/src/main/java/com/mile/controller/writername/WriterNameController.java
  module-common/build.gradle
  module-common/src/main/java/com/mile/config/filter/PrincipalHandler.java
  module-common/src/main/java/com/mile/config/redis/RedisConfig.java
  module-common/src/main/java/com/mile/config/web/WebConfig.java
  module-common/src/main/java/com/mile/exception/message/ErrorMessage.java
  module-common/src/main/java/com/mile/exception/model/TooManyRequestException.java
  module-common/src/main/java/com/mile/handler/GlobalExceptionHandler.java
  module-common/src/main/java/com/mile/interceptor/DuplicatedInterceptor.java
Labels: high

#355 #353 [feat] 엔드포인트 동일로 발생하는 오류 해결
  module-api/src/main/java/com/mile/controller/moim/MoimController.java
  module-auth/src/main/java/com/mile/authentication/CustomJwtAuthenticationEntryPoint.java
Labels: highest

#348 #344 [feat] Too Many Request 테스트 코드 작성
  module-api/src/test/java/com/mile/cocurrency/DuplicatedInterceptorTest.java
Labels: high

#358 [hotfix] 엔드포인트 동일로 발생하는 에러 해결
  module-api/src/main/java/com/mile/controller/moim/MoimController.java
  module-api/src/main/java/com/mile/controller/topic/TopicController.java
  module-api/src/main/java/com/mile/controller/topic/TopicControllerSwagger.java
  module-auth/src/main/java/com/mile/authentication/CustomJwtAuthenticationEntryPoint.java
  module-common/src/main/java/com/mile/utils/SecureUrlUtil.java
  module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustom.java
  module-domain/src/main/java/com/mile/post/repository/PostRepositoryCustomImpl.java
  module-domain/src/main/java/com/mile/post/service/PostGetService.java
  module-domain/src/main/java/com/mile/topic/service/TopicService.java
  module-domain/src/main/java/com/mile/topic/service/dto/PostListInTopicResponse.java
Labels: high

#357 #356 [feat] 글감 순서 변경
  module-domain/src/main/java/com/mile/topic/service/TopicService.java
Labels: highest
