Repository Mile-Writings/Mile-Server, pull requests merged in 2024-07, with the labels that each got.

#422 #421 [refactor] Curious 리팩토링
  module-domain/src/main/java/com/mile/curious/service/CuriousCreator.java
  module-domain/src/main/java/com/mile/curious/service/CuriousRemover.java
  module-domain/src/main/java/com/mile/curious/service/CuriousRetriever.java
  module-domain/src/main/java/com/mile/curious/service/CuriousService.java
Labels: highest

#425 #424 [test] 글모임 도메인 컨트롤러 단위테스트 코드 작성
  module-api/src/test/java/com/mile/cocurrency/DuplicatedInterceptorTest.java
  module-api/src/test/java/com/mile/cocurrency/UniqueNameLockTest.java
  module-api/src/test/java/com/mile/controller/MoimControllerTest.java
  module-domain/src/main/java/com/mile/moim/service/dto/TopicCreateRequest.java
Labels: high

#431 #430 [docs] 리드미 수정
  README.md
Labels: documentation

#427 #426 [refactor] 사용자 글모임 list 조회 N+1 해결
  module-domain/src/main/java/com/mile/user/service/UserService.java
  module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
  module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java
Labels: high

#429 #428 [feat] 유저 탈퇴 플로우 수정 및 구현
  module-api/src/main/java/com/mile/controller/user/UserController.java
  module-api/src/main/java/com/mile/controller/user/UserControllerSwagger.java
  module-api/src/main/java/com/mile/controller/user/facade/AuthFacade.java
  module-auth/src/main/java/com/mile/client/google/GoogleSocialStrategy.java
  module-auth/src/main/java/com/mile/client/google/api/GoogleAccessTokenClient.java
  module-auth/src/main/java/com/mile/client/google/api/GoogleRevokeClient.java
  module-auth/src/main/java/com/mile/client/google/api/GoogleUserClient.java
  module-auth/src/main/java/com/mile/client/kakao/KakaoSocialStrategy.java
  module-auth/src/main/java/com/mile/client/kakao/api/KakaoAccessTokenClient.java
  module-auth/src/main/java/com/mile/client/kakao/api/KakaoUnlinkClient.java
  module-auth/src/main/java/com/mile/client/kakao/api/KakaoUserClient.java
  module-auth/src/main/java/com/mile/client/kakao/api/dto/KakaoUserUnlinkResponse.java
  module-auth/src/main/java/com/mile/strategy/LoginStrategy.java
  module-domain/src/main/java/com/mile/comment/repository/CommentRepository.java
  module-domain/src/main/java/com/mile/comment/service/CommentRemover.java
  module-domain/src/main/java/com/mile/commentreply/repository/CommentReplyRepository.java
  module-domain/src/main/java/com/mile/commentreply/service/CommentReplyRemover.java
  module-domain/src/main/java/com/mile/commentreply/service/CommentReplyService.java
  module-domain/src/main/java/com/mile/curious/service/CuriousRemover.java
  module-domain/src/main/java/com/mile/curious/service/CuriousService.java
  module-domain/src/main/java/com/mile/moim/domain/Moim.java
  module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
  module-domain/src/main/java/com/mile/moim/service/MoimRemover.java
  module-domain/src/main/java/com/mile/moim/service/MoimRetriever.java
  module-domain/src/main/java/com/mile/moim/service/MoimService.java
  module-domain/src/main/java/com/mile/post/repository/PostRepository.java
  module-domain/src/main/java/com/mile/post/service/PostRemover.java
  module-domain/src/main/java/com/mile/topic/repository/TopicRepository.java
  module-domain/src/main/java/com/mile/topic/service/TopicRemover.java
  module-domain/src/main/java/com/mile/topic/service/TopicRetriever.java
  module-domain/src/main/java/com/mile/topic/service/TopicService.java
  module-domain/src/main/java/com/mile/user/service/UserRemover.java
  module-domain/src/main/java/com/mile/user/service/UserService.java
  module-domain/src/main/java/com/mile/writername/domain/WriterName.java
  module-domain/src/main/java/com/mile/writername/repository/WriterNameRepository.java
  module-domain/src/main/java/com/mile/writername/service/WriterNameRemover.java
  module-domain/src/main/java/com/mile/writername/service/WriterNameRetriever.java
  module-domain/src/main/java/com/mile/writername/service/WriterNameService.java
Labels: highest

#437 #436 [feat] Context Util에 토큰 검증 로직 추가
  module-api/src/main/java/com/mile/common/utils/ContextHolderUtil.java
Labels: highest

#435 #434 [feat] 글 삭제/수정 권한 조회 변경
  module-api/src/main/java/com/mile/controller/post/PostController.java
  module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
  module-domain/src/main/java/com/mile/post/service/PostService.java
  module-domain/src/main/java/com/mile/post/service/dto/PostAuthenticateResponse.java
  module-domain/src/main/java/com/mile/post/service/dto/WriterAuthenticateResponse.java
Labels: high

#442 #441 [chore] Swagger API Summary 이름 변경
  module-api/src/main/java/com/mile/controller/post/PostControllerSwagger.java
Labels: highest

#440 #438 [feat] 날짜 포맷 16:1 -> 16:01 로 변경
  module-api/src/test/java/com/mile/controller/MoimControllerTest.java
  module-domain/build.gradle
  module-domain/src/main/java/com/mile/moim/repository/MoimRepository.java
  module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustom.java
  module-domain/src/main/java/com/mile/moim/repository/MoimRepositoryCustomImpl.java
  module-domain/src/main/java/com/mile/moim/service/dto/BestMoimPostResponse.java
  module-domain/src/main/java/com/mile/moim/service/dto/MoimMostCuriousPostResponse.java
  module-domain/src/main/java/com/mile/post/service/dto/PostListResponse.java
  module-domain/src/main/java/com/mile/utils/DateUtil.java
Labels: high

#444 #443 [feat] 필명 관련 데이터 삭제 플로우 추가
  module-domain/src/main/java/com/mile/writername/service/WriterNameRemover.java
Labels: highest
